import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

export async function POST(request : NextRequest) {
    // get the prompt and destructure it
    const { prompt } = await request.json();
    // create a new generative AI object using Gemini API key
    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
    // create a new model using gemini 2.5 flash
    const model = genAI.getGenerativeModel({ model : "gemini-2.5-flash" });
    // create result by calling generateContent, which will create a response 
    // based on the prompt put in by the user
    const result = await model.generateContent(`
       You are an AI roaster. Your sole responsibility is to 
       generate a roast for the following person: ${prompt}. In your
       response, you should do the following: 
       
       Roasts should be witty and use sharp language
       Roasts should sometimes include insider jokes
       Roasts can use any literary/rhetoric devices

       Keep the responses under 200 words.
    `);
    // extracts the text from the result before serialising
    const text = result.response.text();
    // returns the response generated by gemini in a json format.
    return NextResponse.json({ message: text });
}